## Referances
1 : https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html#the-basics

2 : http://cs231n.github.io/python-numpy-tutorial/

3 : https://github.com/jrjohansson/scientific-python-lectures

4 : https://github.com/tpcarneiro/Python-Data-Science-and-Machine-Learning-Bootcamp

5 : https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists

In [0]:
import numpy as np
# from numpy import *

In [2]:
python_list = [[1,2,3,4,5], [6,7,8,9,10]]

arr = np.array(python_list) 

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
arr = np.arange(0, 11 , 2)

arr

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.zeros((4,3) , dtype = "int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full((4,3) , 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.linspace(-1,1,10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [9]:
np.logspace(0,10,7,base=np.e)

array([1.00000000e+00, 5.29449005e+00, 2.80316249e+01, 1.48413159e+02,
       7.85771994e+02, 4.16026201e+03, 2.20264658e+04])

In [10]:
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [11]:
np.random.rand(2,2,2)

array([[[0.20655542, 0.32667475],
        [0.57289309, 0.12258695]],

       [[0.10116776, 0.21060318],
        [0.656938  , 0.77973861]]])

In [12]:
np.random.randn(2,3)

array([[-0.45647777, -0.96196679, -1.36063938],
       [-0.59389869,  0.20748412,  0.76573745]])

In [0]:
arr = np.random.randint(0,10,(4,3))

In [14]:
print(arr)
arr.reshape(6,2)

[[2 0 7]
 [3 7 1]
 [6 1 9]
 [6 6 1]]


array([[2, 0],
       [7, 3],
       [7, 1],
       [6, 1],
       [9, 6],
       [6, 1]])

In [15]:
arr = np.random.randint(0,100,(4,3))
print(arr)
print(arr.min())
print(arr.argmin())

[[14 77 41]
 [80 45 52]
 [60 90 14]
 [40 99 45]]
14
0


In [16]:
arr.ndim

2

In [17]:
arr.size

12

In [18]:
arr = np.random.rand(4,3)
arr.dtype

dtype('float64')

In [19]:
arr.itemsize

8

In [20]:
arr2 = arr

print(arr.data)
print(arr2.data)

In [21]:
sample_arr = np.random.randint(0,100,10)

sample_arr

array([ 3, 12,  8, 39,  2,  7, 29, 74, 65, 41])

In [22]:
for i in range(len(sample_arr)):
    print(sample_arr[i])

3
12
8
39
2
7
29
74
65
41


In [23]:
print(sample_arr)
sample_arr[5:]

[ 3 12  8 39  2  7 29 74 65 41]


array([ 7, 29, 74, 65, 41])

In [24]:
arr = sample_arr.copy()

arr[:] = 1000

print(sample_arr)
print(arr)

[ 3 12  8 39  2  7 29 74 65 41]
[1000 1000 1000 1000 1000 1000 1000 1000 1000 1000]


In [25]:
arr2d = np.random.randint(0,100,(5,5))
arr2d

array([[18, 58, 10, 82, 16],
       [75, 20, 75, 90,  4],
       [68,  2, 72, 95, 79],
       [80, 18,  0, 34,  4],
       [61, 78, 28, 33, 39]])

In [26]:
# print(arr2d)
arr2d[1:3,1:3]

array([[20, 75],
       [ 2, 72]])

In [27]:
arr = np.arange(0,11)
bool_arr = arr > 4

arr2 = arr[arr < 4]

arr2

array([0, 1, 2, 3])

In [0]:
## https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [60]:
arr = np.arange(1,13).reshape(4,3)
arr2 = np.arange(1,13).reshape(4,3)

print(arr)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
