## Referances
1 : https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html#the-basics

2 : http://cs231n.github.io/python-numpy-tutorial/

3 : https://github.com/jrjohansson/scientific-python-lectures

4 : https://github.com/tpcarneiro/Python-Data-Science-and-Machine-Learning-Bootcamp

5 : https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists

In [0]:
import numpy as np
# from numpy import *

In [20]:
python_list = [[1,2,3,4,5], [6,7,8,9,10]]

arr = np.array(python_list) 

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
arr = np.arange(0, 11 , 2)

arr

array([ 0,  2,  4,  6,  8, 10])

In [22]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.full((4,3) , 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
logspace(0,10,5 , base=e)

array([1.00000000e+00, 1.21824940e+01, 1.48413159e+02, 1.80804241e+03,
       2.20264658e+04])

In [41]:
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [44]:
np.random.rand(2,2,2)

array([[[0.29429789, 0.24900164],
        [0.15230494, 0.27723148]],

       [[0.8690257 , 0.79175034],
        [0.59270826, 0.87092598]]])

In [46]:
np.random.randn(2,3)

array([[ 1.00722181, -1.60577895, -0.58899839],
       [-1.36674114, -0.82767965, -1.55158097]])

In [0]:
arr = np.random.randint(0,10,(4,3))

In [91]:
print(arr)
arr.reshape(6,2)

[[9 4 9]
 [9 5 3]
 [0 2 7]
 [9 2 3]]


array([[9, 4],
       [9, 9],
       [5, 3],
       [0, 2],
       [7, 9],
       [2, 3]])

In [104]:
arr = np.random.randint(0,100,(4,3))
print(arr)
print(arr.min())
print(arr.argmin())

TypeError: ignored

In [101]:
arr.ndim

2

In [102]:
arr.size

12

In [105]:
arr = np.random.rand(4,3)
arr.dtype

dtype('float64')

In [108]:
arr.itemsize

8

In [110]:
arr2 = arr

print(arr.data)
print(arr2.data)